version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'develop'
    groups:
      sanity:
        patterns:
          - 'sanity'
          - '@sanity/vision'
          - 'groq'
          - '@sanity/client'
      prisma:
        patterns:
          - 'prisma'
          - '@prisma/client'
