name: Run E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  playwright-e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: 'Preview'
    if: github.event.deployment_status.state == 'success'
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_URL_UNPOOLED: ${{ secrets.DATABASE_URL_UNPOOLED }}
      VENDOR_EMAIL_ADDRESS: ${{ secrets.VENDOR_EMAIL_ADDRESS }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      NEXT_PUBLIC_SANITY_DATASET: ${{ vars.NEXT_PUBLIC_SANITY_DATASET }}
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ vars.NEXT_PUBLIC_SANITY_PROJECT_ID }}
      FOXPOST_API_URL: ${{ secrets.FOXPOST_API_URL }}
      FOXPOST_API_USERNAME: ${{ secrets.FOXPOST_API_USERNAME }}
      FOXPOST_API_PASSWORD: ${{ secrets.FOXPOST_API_PASSWORD }}
      FOXPOST_API_KEY: ${{ secrets.FOXPOST_API_KEY }}
      PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm run test
